# Site Settings
title: "Sean Watson | Chemical Engineering Student"
locale: "en-US"
url: "https://sean-david-watson.github.io"
baseurl: ""

# Site Author Profile Sidebar
author:
  name: "Sean Watson"
  avatar: "bio-photo.jpg" # We will upload your photo for this later!
  bio: "Incoming Chemical Engineering Student at Tennessee Tech University | Eagle Scout"
  location: "Kingsport, TN"
  employer: "Tennessee Tech University"
  uri: "https://sean-david-watson.github.io"
  email: "seandavidwatson0515@gmail.com"
  linkedin: "sean-watson-65082140b" # Your exact LinkedIn handle
  github: "Sean-David-Watson"

# Site Extras
include: [".htaccess"]
exclude: ["markdown_generator", "Rakefile", "Gemfile", "Gemfile.lock", "vendor", "vendor/bundle", "vendor/cache", "vendor/gems", "vendor/ruby"]
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed

# Navigation Links
navigation:
  - title: "About"
    url: /
  - title: "Education & Experience"
    url: /resume/
  - title: "Projects"
    url: /publications/ # We repurpose the 'publications' page for STEM projects later!

# Reading Files
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/
visible_pages: 4
